### PR TITLE
Added threatconnect.com

### PR DESCRIPTION
**Pull request by SangramChavan**
Threat intelligence: It is designed for individual researchers, analysts, and organizations who are starting to learn about cyber threat intelligence.

### CODE REVIEW

**Comment by sbilly** [comment]
It's open-sourced ?

**Comment by SangramChavan** [comment]
Not opensource

**Comment by SangramChavan** [comment]
but it has a free tire

**Comment by Chan9390** [comment]
Is it eligible to be on the list ? From https://threatconnect.com/platform/editions/#comparisonchart I could see that it has more benefits for paid users.

**Pull request closed without merging**
