### PR TITLE
Add XSS detection tool - Cyclops

### PR DESCRIPTION
**Pull request by v8blink**
Name: Cyclops
Type:Discovery/XSS
Description: The Cyclops is a web browser with XSS detection feature, it is chromium-based xss detection that used to find the flows from a source to a sink.
github:https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking

### CODE REVIEW

**Comment by v8blink** [comment]
@sbilly are you still active on this repository ? Or do you have other maintainers to handle the pending PRs ?

**Comment by sebix** [comment]
> @sbilly are you still active on this repository ? Or do you have other maintainers to handle the pending PRs ?

:/

@sbilly will take the time to review the PR once he has time. There is no reason to put pressure except if your intentions are dishonorable.

**Comment by sbilly** [comment]
Is that an open source software?

**Comment by v8blink** [comment]
Currently not open source, will open source in the future.

**Comment by Lissy93** [comment]
Sounds suspect...

**Comment by v8blink** [comment]
@Lissy93 where is suspicious？

**Pull request merged**
