### PR TITLE
Add Content Disarm & Reconstruct category

### PR DESCRIPTION
**Pull request by PunKeel**
With DocBleach, ReSec and OPSWAT

### CODE REVIEW

**Comment by PunKeel** [comment]
Up @sbilly? :-/

**Comment by sbilly** [comment]
Is resec and opswat commercial software ?

This list is for opensource and free software only.

**Comment by PunKeel** [comment]
Sorry about this. In this list, DocBleach is indeed the only OSS one.
I am the creator of DocBleach, and didn't want to add it alone, so I listed in OpsWat & ReSec

**Comment by sbilly** [comment]
You can send a new pull request.

**Pull request closed without merging**
