### PR TITLE
docs: Add Substation to Big Data

### PR DESCRIPTION
**Pull request by jshlbrd**

### CODE REVIEW

**Review by andrzejsydor — APPROVED** [review]

**Comment by jshlbrd** [comment]
@andrzejsydor thanks for the approval! @sbilly good to merge?

**Review by 69camau — APPROVED** [review]

**Review by andrzejsydor — APPROVED** [review]

**Review by 69camau — APPROVED** [review]
Ffd

**Comment by sebix** [comment]
That pattern of reviews smells...

**Comment by jshlbrd** [comment]
> That pattern of reviews smells...

love the smell of open source in the morning

**Pull request merged**
